[project]
name = "narocheckerbot"
version = "0.1.0"
description = "Add your description here"
readme = "Readme.md"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "feedparser>=6.0.11",
    "ruamel-yaml>=0.18.14",
]

[dependency-groups]
dev = ["ruff>=0.12.0"]
